tap "go-delve/delve"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"


brew "adns"
brew "openssl@1.1"
brew "gettext"
brew "readline"
brew "sqlite"
brew "ansible"
brew "node"
brew "autocode"
brew "autoconf"
brew "automake"
brew "bash"
brew "bat"
brew "binutils", link: true
brew "cmake"
brew "coreutils"
brew "ctags"
brew "dbus"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "doxygen"
brew "ed", link: true
brew "emojify"
brew "exa"
brew "exercism"
brew "libevent"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fisherman", args: ["HEAD"]
brew "flex"
brew "fswatch"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gifsicle"
brew "git"
brew "glances"
brew "gnu-sed"
brew "gnu-time"
brew "libevent"
brew "libusb"
brew "npth"
brew "gnupg"
brew "golang-migrate"
brew "gpg-agent"
brew "libtool"
brew "graphviz"
brew "grc"
brew "highlight"
brew "httpie"
brew "imagemagick"
brew "jo"
brew "jq"
brew "spidermonkey"
brew "jsawk"
brew "json-table"
brew "lbzip2"
brew "lftp"
brew "libssh2"
brew "libusb-compat"
brew "lynx"
brew "make"
brew "mas"
brew "mercurial"
brew "miller"
brew "mitmproxy"
brew "mosh"
brew "most"
brew "mtr"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nghttp2"
brew "optipng"
brew "packer"
brew "parallel"
brew "pbzip2"
brew "peco"
brew "perl"
brew "pgcli"
brew "pidof"
brew "pigz"
brew "pinentry-mac"
brew "pkg-config"
brew "pngcrush"
brew "pngquant"
brew "progress"
brew "prototool"
brew "proxychains-ng"
brew "psutils"
brew "pv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rpm2cpio"
brew "rust"
brew "screenfetch"
brew "shellcheck"
brew "siege"
brew "smartmontools"
brew "speedtest-cli"
brew "starship"
brew "swiftformat"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "thefuck"
brew "utf8proc"
brew "tmux"
brew "tokei"
brew "vegeta"
brew "watch"
brew "wget"
brew "xsv"
brew "yarn"
# brew "youtube-dl"
brew "golangci/tap/golangci-lint"

cask "1password"
cask "aerial"
cask "alfred"
cask "anaconda"
cask "authy"
cask "bartender"
cask "betterzip"
cask "boom-3d"
cask "calibre"
cask "cryptomator"
cask "discord"
cask "disk-inventory-x"
cask "docker"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "itsycal"
cask "java"
cask "keka"
cask "little-snitch"
cask "micro-snitch"
cask "notion"
cask "private-internet-access"
cask "qladdict"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlmobi"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "rescuetime"
cask "rocket"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "splice"
cask "spotify"
cask "spotify-notifications"
cask "sublime-merge"
cask "suspicious-package"
cask "swiftformat-for-xcode"
cask "tripmode"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "wkhtmltopdf"
cask "xld"
cask "xquartz"
cask "zoomus"

mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Developer", id: 640199958
mas "Logic Pro X", id: 634148309
mas "Numbers", id: 409203825
mas "OmniGraffle", id: 1142578753
mas "Pages", id: 409201541
mas "Paste JSON as Code • quicktype", id: 1330801220
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "WireGuard", id: 1451685025
